apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      containers:
        - name: jupyterlab-worker
          image: >-
            jupyter/datascience-notebook
          ports:
            - containerPort: 8888
              protocol: TCP
          env:
            - name: JUPYTERLAB_PASSWORD
              value: admin
          command: ["start-notebook.sh"]
          args: ["-e", "PASSWORD=$JUPYTERLAB_PASSWORD", '--LabApp.check_for_updates_class="jupyterlab.NeverCheckForUpdate"']
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
