kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-to-scc-anyuid
subjects:
  - kind: ServiceAccount
    name: jupyterhub
roleRef:
  kind: Role
  name: jupyterhub
  apiGroup: rbac.authorization.k8s.io
